// <auto-generated />
using System;
using HastaTakip.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HastaTakip.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230705075029_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HastaTakip.Models.Hasta", b =>
                {
                    b.Property<int>("hasta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("hasta_id"));

                    b.Property<DateOnly>("dogum_tarihi")
                        .HasColumnType("date");

                    b.Property<string>("hasta_ad_soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("hasta_tc")
                        .HasColumnType("integer");

                    b.HasKey("hasta_id");

                    b.ToTable("hastalar");
                });
#pragma warning restore 612, 618
        }
    }
}
